name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Set this to your default branch

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      # Create a .env file with default values for build
      - name: Create environment file
        run: |
          echo "PORT=3000" >> .env
          echo "NODE_ENV=production" >> .env
          echo "GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}" >> .env
          echo "GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }}" >> .env
          echo "GOOGLE_REDIRECT_URI=https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/api/auth/callback" >> .env
          echo "SESSION_SECRET=${{ secrets.SESSION_SECRET }}" >> .env
          echo "CORS_ORIGIN=https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}" >> .env

      # This step copies the necessary files to the 'build' directory
      # You might need to adjust this based on how your build process works
      - name: Prepare build directory
        run: |
          mkdir -p build
          cp -r public/* build/
          cp -r server build/
          cp package.json build/

      # Configure GitHub Pages
      - name: Setup GitHub Pages
        uses: actions/configure-pages@v3

      # Upload artifact
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: "build"

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
